name: CI

on:
  pull_request_target:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'refs/pull/${{ github.event.number }}/merge'
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Use composer
      uses: php-actions/composer@v5
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: ./phpunit.xml
        php_version: 7.4
        version: 9.5.21
        memory_limit: 256M
    